frontpage_cards:
  - title: Nachhaltigkeitsstrategie Pirmasens 2030
    href: Nachhaltigkeitsstrategie-Pirmasens.pdf
    thumbnail_src: /Nachhaltigkeitsstrategie-Pirmasens.jpg
  - title: SDG-Modellregion Pfälzerwald
    href: SDG_Biodiv_05.12.2023.pdf
    thumbnail_src: /SDG_Biodiv_05.12.2023.jpg
  - title: Die Verankerung der Agenda 2030 in die kommunale Praxis
    href: SDG_Monitoring_09.06.2024.pdf
    thumbnail_src: /SDG_Monitoring_09.06.2024.jpg
